ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect

def redirect_shop_page(request):
    return redirect('/shop')

urlpatterns = [
    path('admin', admin.site.urls),
    path('shop', include('shop.urls')),
    path('', redirect_shop_page),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "ecommerce administration"

shop/urls.py
from django.urls import path, include
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shop_page, name='shop_page'),
    path('/policy', views.policy, name='policy'),
    path('/<produit_id>/<slug>', views.produit_page, name='produit_page'),
]

shop/models.py
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.core.validators import RegexValidator
from django.core.validators import MinValueValidator
import os
import datetime
from ckeditor.fields import RichTextField

# Create your models here.

def slugify_unicode(str):
    str = str.replace(" ", "-")
    str = str.replace(",", "-")
    str = str.replace("(", "-")
    str = str.replace(")", "")
    str = str.replace("؟", "")
    return str

class Produit(models.Model):
    name = models.CharField(max_length=200)
    prix = models.PositiveIntegerField()
    prix_remise = models.PositiveIntegerField(blank=True, null=True)
    slug = models.SlugField(blank=True)
    # description = models.TextField(blank=True, null=True)
    description = RichTextField()
    quantité_en_stock = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='shop/produits/')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify_unicode(self.name)
        super(Produit, self).save(*args, **kwargs)


COMMANDE_ETAT = (
    ("en attente", "en attente"),
    ("confirmé", "confirmé"),
    ("non confitmé", "non confitmé"),
)


class Commande(models.Model):
    produit = models.ForeignKey(
        Produit, on_delete=models.SET_NULL, null=True)
    full_name = models.CharField(max_length=200)

    phone_regex = RegexValidator(
        regex=r'^0?\d{10,}$',
        message="votre numero de telephone doit commancer par un 0 et contenir 10 chifres"
    )
    phone_number1 = models.CharField(
        validators=[phone_regex], max_length=10)
    phone_number2 = models.CharField(
        validators=[phone_regex], max_length=10, blank=True, null=True)

    adresse = models.CharField(max_length=500)
    quantité = models.PositiveIntegerField(
        default=1, validators=[MinValueValidator(1), ])
    etat = models.CharField(choices=COMMANDE_ETAT,
                            default="en attente", max_length=50)
    date_commande = models.DateTimeField(default=datetime.datetime.now())
    date_confirmation = models.DateTimeField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.etat == "confirmé":
            self.date_confirmation = datetime.datetime.now()
        super(Commande, self).save(*args, **kwargs)

shop/forms.py
from django import forms
from .models import Commande


class CommandeForm(forms.ModelForm):

    class Meta:
        model = Commande
        fields = ("full_name", "adresse", "phone_number1",
                  "phone_number2", "quantité",)

    def __init__(self, *args, **kwargs):
        super(CommandeForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].widget.attrs['placeholder'] = "Nom et Prenom"
        self.fields['adresse'].widget.attrs['placeholder'] = "Adresse"
        self.fields['phone_number1'].widget.attrs['placeholder'] = "Numero De Telephone"
        self.fields['phone_number2'].widget.attrs[
            'placeholder'] = "Second Numero De Telephone (optionel)"

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import Produit, Commande
from .forms import CommandeForm


# Create your views here.


def shop_page(request):
    produits = Produit.objects.all().order_by('-id')
    context = {
        "produits": produits
    }

    return render(request, 'shop.html', context)


def produit_page(request, produit_id, slug):
    produit = get_object_or_404(Produit, id=produit_id, slug=slug)
    if request.method == 'POST':
        form = CommandeForm(request.POST)
        if form.is_valid():
            pass
            full_name = form.cleaned_data.get('full_name')
            phone_number1 = form.cleaned_data.get('phone_number1')
            phone_number2 = form.cleaned_data.get('phone_number2')
            adresse = form.cleaned_data.get('adresse')
            quantité = form.cleaned_data.get('quantité')

            commande = Commande.objects.create(produit=produit,
                                               full_name=full_name,
                                               phone_number1=phone_number1,
                                               phone_number2=phone_number2,
                                               adresse=adresse,
                                               quantité=quantité)
            messages.add_message(request, messages.SUCCESS,
                                 'Votre commande a bien été prise')
            return redirect('/shop/{}/{}'.format(produit_id, slug))
    else:
        form = CommandeForm()

    context = {
        "produit": produit,
        "form": form,
        # "messages": messages
    }

    return render(request, 'produit-item.html', context)

def policy(request):
    return render(request, 'policy.html')

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css"
        integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous" />


    <!-- sections styles  -->

    <title>{% if produit.name %} {{ produit.name }} | {% endif %}shop</title>
</head>

<body>
    <header>
        <div class="logo">
            <a href="{% url 'shop:shop_page' %}"><img src="{% static 'images/logo.jpg' %}" alt=""></a>
        </div>

        <div class="home-icon">
            <a href="{% url 'shop:shop_page' %}"><i class="fas fa-home"></i></a>
        </div>
    </header>

    {% block content %}

    {% comment %} here commes the content from the other pages {% endcomment %}

    {% endblock %}

    <footer>
        <div class="container">
            <div class="copyright">
                <h3 class="title mg-bottom">Paramed-DZ</h3>
                <p>Copyright &copy; 2021</p>
            </div>
            <div>
                <p class="mg-bottom">contactez nous sur notre numéro de téléphone:</p>
                <ul>
                    <li>0540188065</li>
                </ul>
            </div>

            <div>
                <p class="mg-bottom">ou bien sur nos résaux sociaux:</p>
                <div class="social-media">
                    <a href="https://www.facebook.com/paramed.dz0001/" target="_blank"><i class="fab fa-facebook"></i></a>
                    <a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i></a>
                </div>
            </div>

            <div>
                <a href="{% url 'shop:policy' %}">سياسة الخصوصية</a>
            </div>

        </div>
    </footer>

</body>

</html>

shop/templates/policy.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% comment %} css style code file {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/policy-style.css' %}">

    <section class="policy">
        <div class="container">
            <h2>سياسة الخصوصية</h2>

            <h3 class="under-line">سياسة الخصوصية:</h3>
            <p>
                شكرًا لدخولك إلى موقع <strong>Paramed-dz</strong> إنّ موقعنا يحترم خصوصيّتك
                ويسعى لحماية بياناتك الشخصية.
                لمعرفة المزيد، يُرجى قراءة سياسة الخصوصيّة أدناه.
            </p>
            <p>
                وضح سياسة الخصوصيّة كيفية جمع واستخدام 
                بياناتك الشخصية (تحت ظروفٍ معينةٍ). كما تذكرُ أيضًا الإجراءات 
                المتبعة لضمان خصوصية معلوماتك. وأخيرًا، تُحدّد هذه السياسة الخيارات 
                المتاحة لكَ فيما يتعلَّق بجمع البيانات الشخصية واستخدامها والكشف عنها. 
                فمن خلال زيارتك للموقع مباشرةً أو عن طريق موقعٍ آخر، 
                فأنتَ توافق على الممارسات الموضحة في هذه السياسة.
            </p>
            <p>
                إن حماية بياناتك أمرٌ هامٌ جدًّا بالنسبة إلينا. 
                ومن ثم، يتم استخدام اسمك وغيره من المعلومات التي تتعلّق 
                بك وفقًا للّنحو المبيّن في سياسة الخصوصيّة. وسنقوم بجمع المعلومات 
                عند الضرورة أو إذا كانت ذات صلةٍ ضرورية مباشرةٍ بمعاملاتنا معكَ
            </p>
            <p>
                وسنقوم بالاحتفاظ ببياناتك وفقًا للقانون أو لاستخدامها للأغراض التي جُمعت لأجلها.
            </p>
            <p>
                كما يمكنك تصفح الموقع دون الحاجة إلى تقديم أيّة بيانات شخصيّة. وتبقى هويّتك 
                الشخصية مجهولة طيلة زيارتك للموقع ولا يتم كشفها إلا إذا كنتَ تملك حسابًا 
                إلكترونياً خاصًا على الموقع تدخل إليه بواسطة اسم المستخدم وكلمة السرّ.
            </p>

            <h3 class="under-line"> أولا - البيانات التي نجمعها:</h3>
            <p>
                قد نحتاج لجمع المعلومات الخاصة بكَ إذا أردت تسجيل طلب شراء لسلعة من موقعنا.
            </p>
            <p>
                ونقوم بجمع وتخزين ومعالجة بياناتك اللازمة لمتابعة شرائك من موقعنا لتأمين 
                أية مطالب محتملة قد تظهر لاحقاً، ولتزويدكَ بالخدمات المتوفرة لدينا. 
                وقد نقوم بجمع معلومات شخصية تتضمَّن، على سبيل المثال وليس الحصر، الاسم 
                والجنس وتاريخ الميلاد وعنوان البريد الإلكتروني والعنوان البريدي وعنوان 
                التسليم (إذا كان مختلفًا) ورقم الهاتف ورقم الهاتف المحمول ورقم الفاكس 
                وتفاصيل الدفع وتفاصيل عن بطاقات الدفع أو تفاصيل عن الحساب المصرفي.
            </p>
            <p>
                ونستخدم المعلومات التي تقدِّمها لتمكننا من معالجة طلباتك ولتزويدكَ بخدمات 
                ومعلومات معروضة على موقعنا والتي تطلبها أنت. وعلاوةً على ذلك، 
                سنستخدم المعلومات التي تقدَّمها في إدارة حسابك معنا 
                وللتحقّقَ من المعاملات المالية التي تُجريها على الإنترنت 
                وعمليات تدقيق تحميل البيانات من الموقع وتحديد هويّة زائري 
                الموقع وتطوير تصميمات صفحات الموقع و/أو محتوياته وتخصيصها 
                للمستخدمين. ونقوم بأبحاث عديدة متعلقة بالتركيبة السكانية، 
                ونُرسل المعلومات المفيدة أو المطلوبة إلى المستخدم، 
                على سبيل المثال معلومات حول المنتجات والخدمات، وذلك في حالة 
                عدم اعتراضك على التواصل معك بشأن ذلك. ويتم التواصل عبر البريد 
                الإلكتروني لتزويدك ببعض التفاصيل حول المنتجات والخدمات الأخرى 
                إذا كنت ترغب في ذلك، وإذا كنتَ تفضّل عدم تلقي أية اتصالات ترويجيّة 
                وتسويقيّة، فيُرجى الانسحاب من هذا الخيار في أي وقتٍ من الأوقات.
            </p>
            <p>
                وقد نعطي اسمك وعنوانك إلى طرفٍ ثالث بهدف تسليمكَ 
                طلب شرائك على سبيل المثال، عامل التسليم أو المورِّد.
            </p>
            <p>
                ويقوم وكيل شبكتنا الدولية 
                بإدارة المعاملات المالية عبر الإنترنت. وما عليك فعله 
                هو تقديم معلومات دقيقة وغير مضلّلة للوكيل أو الموقع، 
                ويجدر بك تحديثها على الدوام وابلاغنا بالتغييرات.
            </p>
            <p>
                قد نتمكن من تخزين التفاصيل المتعلّقة بطلبك الحالي على موقعنا 
                ولكن لا يمكننا استعادتها مباشرةً لأسبابٍ أمنيّة. وبتسجيل 
                الدخول إلى حسابك على الموقع يمكنك الاطلاع على المعلومات وتفاصيل 
                مشترياتك التي طلبتها أو التي ستتقدَّم بها قريبًا. وبمقدورك أيضاً 
                إدارة تفاصيل عنوانك، والتفاصيل المصرفية وأية نشرةٍ إخباريةٍ 
                قد اشتركت فيها. كما يجدر بك التعهُّد بالتعامل بسريّة تامة 
                عند الدخول إلى بياناتك الشخصيَّة فلا تجعلها متاحة لطرف ثالث 
                غير مصرَّح به. ولا نتحمَّل أية مسؤولية ناتجة عن سوء استخدام 
                كلمات السر إلا إذا كان سوء الاستخدام هذا ناشئ عن خطأ منّا.
            </p>

            <h3>استخدامات أخرى لمعلوماتك الشخصيَّة :</h3>
            <p>
                قد نستخدم معلوماتك الشخصيَّة في استطلاعات 
                الرأي وأبحاث التسويق، بناءً على رغبتك، لأغراضٍ إحصائية مع ضمان 
                سريتها التامة، كما يحق لك الانسحاب في أيّ وقت. ولا نقوم بإرسال 
                أي إجابات إلى أي طرف ثالث. ولا يتم الإفصاح عن عنوان بريدك 
                الإلكتروني إلا إذا رغبتَ في المشاركة في المسابقات. ونحتفظ بإجابات 
                استطلاعات الرأي في مكانٍ منفصل تمامًا عن بريدك الإلكتروني الخاص.
            </p>
            <p>
                وقد نقوم بإرسال معلومات عنَّا، أو عن الموقع أو مواقعنا الأخرى أو عن منتجاتنا 
                أو مبيعاتنا أو عروض بيعنا أو نشراتنا وغير ذلك ممّا له علاقة 
                بالشركات التابعة لمجموعتنا أو شُركائنا. وإذا كنت لا ترغب 
                في الحصول على هذه المعلومات الإضافيّة (أو في أي جزءٍ منها)، 
                فيُرجى الضغط على رابط “إلغاء الاشتراك” الموجود في أي بريد 
                إلكتروني مرسل إليك، وسنتوقّف عن إرسال هذه المعلومات لك في 
                غضون سبع أيام عمل (كل يوم عدا أيام الجمعة والسبت والأعياد 
                الوطنيّة) من تلقي إخطار ك. 
                وسنتواصل معك للاستفسار عن المعلومات في حين عدم وضوحها
            </p>
            <p>
                وقد نستخدم بعض البيانات، مع الحفاظ التام 
                على الخصوصيّة والسريّة على الموقع، لأغراض أخرى بما في ذلك التحقُّق 
                من أماكن تواجد المستخدمين ومتابعة زيارتهم للموقع أو الروابط 
                الواردة في البريد الإلكتروني في حين اشتراكهم لتلقيه، ولتزويد 
                تلك البيانات مجهولة المصدر، التي لا تسمح بتحديد هويّتك الشخصيّة 
                الفعليّة، إلى طرف ثالث كالنّاشرين على سبيل المثال. ومع ذلك، فتلك 
                البيانات لن تؤدي إلى تحديد شخصيتك لأنها غير محدّدة للهوية 
            </p>

            <h3>المنافسات:</h3>
            <p>
                فيما يتعلق بأي منافسة، نستخدم 
                البيانات لإخطار الفائزين وللإعلان عن عروضنا. ويمكنك العثور 
                على مزيد من التفاصيل عن شروط المشاركة في كل منافسة على حدة.
            </p>
            </p>

            <h3>الأطراف الأخرى وروابط المواقع:</h3>
            <p>
                قد ننقل معلوماتك إلى شركات أخرى في مجموعتنا أو 
                إلى وكلائنا والمتعاقدين معنا لمساعدتنا في المعاملات المتعلقة 
                وفقا لبنود سياسة الخصوصية. وقد نلجأ على سبيل المثال إلى طرف 
                ثالث لمساعدتنا في تسليم المنتجات إليك واستلام الدفعات منك و
                استخدامها لأغراض الإحصاءات وأبحاث التسويق أو لمساعدة فريق خدمة 
                العملاء. وقد نحتاج لتبادل المعلومات مع طرف ثالث بهدف الحماية 
                من الاحتيال والحد من مخاطر الائتمان. و في حال تمّ بيع شركتنا 
                أو جزء منها، فقد نضطر لنقل قواعد بياناتنا التي تشمل معلوماتك 
                الشخصيّة. وبخلاف ما هو منصوص عليه في سياسة الخصوصية، لن نقوم 
                ببيع بياناتك الشخصية أو الإفصاح عنها لطرف ثالث دون الحصول على 
                موافقة مسبقة منك إلّا إذا كان ذلك ضروريًا للأغراض المنصوص عليها 
                في سياسة الخصوصيّة هذه، أو إذا طُلب منّا ذلك بحكم القانون. 
                وقد يحتوي الموقع على إعلانات لطرف ثالث أو روابط تؤدِّي إلى مواقعٍ 
                أخرى أو إطارات لمواقعٍ أخرى. ونحيطك علماً بأننا غير مسؤولين 
                عن سياسة الخصوصيّة الخاصة بأي طرف ثالث أو محتوى تلك السياسات 
                المطبّقة في المواقع الأخرى، فضلًا عن أنّنا غير مسؤولين إزاء 
                أي طرف ثالث ننقل إليه بياناتك بما يتوافق مع سياسة الخصوصيّة.
            </p>

            <h3 class="under-line"> ثانيا - ملفات تعريف الارتباط (COOKIES):</h3>
            <p>
                لا يُعتبر قبول ملفات تعريف الارتباط شرطًا أساسيًا لزيارة الموقع. 
                ولكنّنا نشير إلى أنّه لا يمكن استخدام وظائف “السلّة” على الموقع وطلب 
                أي غرض من دون تفعيل ملفات تعريف الارتباط. وتُعتبر ملفات 
                تعريف الارتباط ملفات نصيّة صغيرة تسمح لخادمنا بتحديد 
                حاسوبك كمستخدم فريدٍ عند زيارة صفحات معينة من الموقع. 
                ويخزِّن متصفّحك هذه الملفات على قرص حاسوبك الثابت. ويمكن 
                استخدام ملفات تعريف الارتباط لاكتشاف عنوان بروتوكول الإنترنت (IP)، 
                مما يوفّر لك الوقت عندما تكون على الموقع أو تريد زيارته. ونستخدم ملفات تعريف ا
                لارتباط لضمان راحتك عندما تتصفّح هذا الموقع (لنتذكر على سبيل 
                المثال هويّتك عندما تريد تعديل سلّة تسوقك بدون الحاجة إلى 
                إعادة إدخال عنوان بريدك الإلكتروني) وليس من أجل الحصول على معلومات 
                أخرى عنك أو استخدامها (مثلاً لأغراض التسويق المستهدف). ويمكنك ضبط متصفحك حتى 
                لا يقبل ملفات تعريف الارتباط ولكن هذا من شأنه أن يحدّ من استخدامك للموقع. 
                ونرجو أن تتأكد من أنّ لجوءنا إلى ملفات تعريف الارتباط لا يحتوي 
                على أية معلومات شخصية أو خاصة ويخلو من الفيروسات ويستخدم هذا الموقع 
                خدمة تحليلات جوجل (Google Analytics) وهي خدمة تقدّمها شركة جوجل لتحليل صفحات شبكة الإنترنت. 
                ولتحليل كيفية استخدام المستخدمين للموقع، ترتكز خدمة تحليلات 
                جوجل على ملفات تعريف الارتباط وهي ملفات نصيّة وُضعت على حاسوبك. 
                وستنقل شركة جوجل المعلومات التي تولّدها ملفات تعريف الارتباط 
                عن استخدامك لهذا الموقع (بما في ذلك عنوان بروتوكول الإنترنت) 
                إلى خوادم في الولايات المتحدة حيث سيتم تخزينها. وسوف تستخدم 
                شركة جوجل هذه المعلومات لتقييم استخدامك للموقع، وإعداد 
                تقارير لمشغلي الموقع عن نشاطه وتوفير خدمات أخرى مرتبطة 
                بنشاط الموقع واستخدام الإنترنت. وقد تنقل جوجل أيضاً هذه 
                المعلومات إلى طرف ثالث في حال طُلب منها ذلك بموجب 
                القانون أو في حال عالج طرف ثالث 
                المعلومات بالنيابة عن شركة جوجل. 
                ولن تربط شركة جوجل عنوان بروتوكول 
                الإنترنت خاصتكَ مع أيّة بيانات أخرى تحتفظ بها. 
                ويمكنك رفض استخدام ملفات تعريف 
                الارتباط وذلك عن طريق اختيار الإعدادات المناسبة 
                على متصفحك ولكن ترجو أن تأخذ بعين الاعتبار 
                أنّك عندئذ لن تستطيع الاستفادة من وظيفة 
                الموقع الكاملة. ومن خلال استخدامك هذا 
                الموقع، فأنت توافق على أن تستخدم شركة 
                جوجل بياناتك على النحو المبين والأغراض المفصَّلة أعلاه.
            </p>
            </p>

            <!-- <h3 class="under-line"> ثالثا - الأمان:</h3>
            <p>
                نستخدم تقنيات وإجراءات أمان 
                ملائمة لمنع أي وصول غير مصرَّح به أو غير قانوني لمعلوماتك أو فقدانها 
                أو تدميرها. فعندما نجمع البيانات من خلال الموقع، نقوم بتخزين معلوماتك 
                الشخصية على قاعدة بيانات ضمن خادم إلكتروني آمن. فنستخدم أنظمة جدار 
                الحماية على خوادمنا. وعندما نقوم بجمع تفاصيل بطاقات الدفع إلكترونيًا، 
                فإننا نحميها من خلال استخدام التشفير، مثل طبقة مآخذ التوصيل الآمنة (SSL). فيصعب بالتّالي على أيّ متسلّلٍ فكّ تشفير معلوماتك بما 
                أنّنا لا نستطيع ضمان الحماية بنسبة مئة في المئة. وننصحك بشدَّة بعدم إرسال كل تفاصيل بطاقة 
                الائتمان أو بطاقة السحب الآلي عندما تتواصل معنا إلكترونيًا ومن دون تشفير. ونضع ضمانات ماديّة 
                وإلكترونية وإجرائيّة مباشرة على عملية جمع معلوماتك وتخزينها 
                والإفصاح عنها. وتتطلّب إجراءاتنا الأمنية أن نطلب منك أحياناً إثبات هويتك قبل أن نُفصِح لك 
                عن معلوماتك الشخصية. وتقع على عاتقك مسؤولية 
                حماية كلمتك السريّة وحاسوبك من أيّ استخدام غير مصرَّح به.
            </p> -->

            <h3 class="under-line">ثالثا - حقوق العميل:</h3>
            <p>
                في حال شعورك بالقلق على بياناتك، يحق لك طلب الوصول إلى البيانات الشخصيّة 
                التي نحملها عنك أو سبق ونقلتها إلينا. ويحق لك أن تطلب منَّا تصحيح أي أخطاء 
                في بياناتك الشخصيّة ويتم ذلك مجانًا. ولك الحق أيضًا في مطالبتنا، 
                في أي وقت، بالتوقُّف عن استخدام بياناتك الشخصية لأغراض تسويقيّة مباشرة.
            </p>
            <br>
            <p>
                للاستفسار أو لمعلومات أكثر، يرجى مراسلتنا على بريدنا الالكتروني:
            </p>
            <strong>farhiayoub22@gmail.com</strong>
        </div>
    </section>
{% endblock %}
  

shop/templates/produit-item.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% comment %} css style code file {% endcomment %}
<link rel="stylesheet" href="{% static 'css/produit-item-style.css' %}">

{% comment %} jquery {% endcomment %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{% if messages %}
<div class="success-messages">
    <ul>
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
</div>
{% endif %}

<section class="produit-item">
    <div class="container">
        <div class="produit-item__detail">
            <div class="produit-item__image">
                <img src="{{ produit.image.url }}" alt="">
            </div>
            <h2 class="produit-item__name">{{ produit.name }}</h2>
            <div class="produit-item__price">
                {% if produit.prix_remise %}
                <span class="produit-item__price discount">{{ produit.prix }}DA</span> -
                <span class="produit-item__price">{{ produit.prix_remise }}DA</span>
                {% else %}
                <span class="produit-item__price">{{ produit.prix }}DA</span>
                {% endif %}
            </div>
            <p class="produit-item__description">
                {{ produit.description|safe }}
            </p>
        </div>
        <div class="produit-item__commande" id="form">
            <h2>pour commader ce produit veuillez remplire ce formulaire</h2>
            <form action="" method="post">
                {% csrf_token %}
                {% for f in form %}
                {% if f.label == 'Quantité' %}
                <label for="">Quantité: </label>
                {% endif %}

                {{ f }}
                {% endfor %}
                <div class="errors">
                    {% for f in form %}
                    {{ f.errors }}
                    {% endfor %}
                </div>
                <input type="submit" value="Commander">
            </form>
        </div>
        <a href="#form" class="commande-button display-phone">أطلب الأن</a>
    </div>
</section>

{% comment %}
<script>
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();

            document.querySelector(this.getAttribute('href')).scrollIntoView({
                behavior: 'smooth'
            });
        });
    });
</script> {% endcomment %}
<script type="text/javascript" src="{% static 'js/scroll-smooth.js' %}"></script>

{% endblock %}

shop/templates/shop.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% comment %} css style code file  {% endcomment %}
<link rel="stylesheet" href="{% static 'css/shop-style.css' %}">


<section class="hero">
    <div>
        <h2 class="hero__title">Bienvenu Chez Paramed-DZ!</h2>
        <p class="hero__description">Votre platforme pour tout vos poduits bio et cosmétiques</p>
    </div>
</section>

<section class="produits">
    <div class="section-title">
        <h2 class="title">Nos Produits</h2>
    </div>

    <div class="produits__grid">
    {% for produit in produits %}
        <div class="produit-card">
            <a href="{% url 'shop:produit_page' produit.id produit.slug %}">
                <img class="produit-card-image" src="{{ produit.image.url }}" alt="" title="">
                <h3 class="produit-card-title">{{ produit.name }}</h3>
                <div>
                    {% if produit.prix_remise %}
                        <span class="produit-card-price discount">{{ produit.prix }}DA</span> -
                        <span class="produit-card-price">{{ produit.prix_remise }}DA</span>
                    {% else %}
                        <span class="produit-card-price">{{ produit.prix }}DA</span>
                    {% endif %}
                </div>
                <button class="commande-button">أطلب الأن</button>
            </a>
        </div>
    {% endfor %}

    </div>
</section>

{% endblock %}